### ISSUE TITLE
Spells changed to cold through Sorc or Wizard abilities do not qualify for Rime Spell Feat

### ISSUE THREAD

**Issue by Reginude** [Vek17/TabletopTweaks-Base#370]
**Describe the bug**
I'm not sure if this is technically a bug, but seems like an oversight of a sort. When using the sorcerer bloodline or Wizard elemental specialist to change a non-cold spell into a cold spell, there is no way to apply the rime spell feat. I understand this is because they lack the cold descriptor in the spell menu as that represents the unadulterated spell. Perhaps lift the cold descriptor restriction, and just have it proc on cold damage as per rest of feat description?

**To Reproduce**
Cannot apply rime spell to fireball for example, which makes sense - but same is true for a fireball made cold through in-game abilities.

**Expected behavior**
To be able to apply rime spell to spells that are turned into cold spells through abilities.

**Screenshots**
NA

**Additional context**
NA

**Comment by Vek17** [comment]
This is a weird area because you cannot legally prepare a spell without the cold descriptor with Rime even if you later convert it, but in principal you likely could modify the spell spontaneously with an elemental bloodline and then apply spontaneous metamagic. The issue is the 2nd case is not really mechanically supported and enabling it breaks the first case which is imo generally more important. 

The other usability thing is being able to apply Rime to spells where it would do nothing is bad UX design.

**Comment by Reginude** [comment]
Thank you for the comment, this makes sense. I separately tested this with scorching ray (cold) and burning hands (cold) and was surprised that this case did not work - as they have the cold descriptor. This seems like a different case to above, so I posted separately.

I know fire is much better, but I'm really trying to make a cold mage and rime spell work. Thank you very much for putting this mod together.

**Comment by Vek17** [comment]
So in terms of max potential optimization Cold is actually the highest damage option (using primarily converted spells), and Rime is already one of the strongest metamagic so I am fairly cautious about just adding more fuel to that. It may change in the future but for now I think it makes more sense to let Rime be very powerful, but fairly limited in what spell it can be used on.
