### ISSUE TITLE
[Bug] Alternate capstones unavailable to ranger subclasses

### ISSUE THREAD

**Issue by Nbzor** [Vek17/TabletopTweaks-Base#445]
Espionage Experts, as well as Flamewarden rangers, cannot pick alternate capstones at level 20 (because of the base class capstone "Master Hunter" being replaced by a different capstone for those subclasses.)

This seems to also affect some subclasses of other classes such as Inquisitor and Oracle, whose capstones get changed or even disabled in the base game, although in those cases it is unclear to me whether the unavaibility of alternate capstones is intended or a bug.

**Comment by Vek17** [comment]
This is intended by the alternative captone rules and is stated in game.
For reference:

When a character reaches the 20th level of a class, she gains a powerful
class feature or ability, sometimes referred to as a capstone. When a
character reaches 20th level, the following new abilities can be selected
instead of the standard 20th level class ability which would normally be
gained. In some cases, a capstone specifies what ability it replaces.

A character can’t select an alternative capstone if she has previously
traded away her class capstone via an archetype.

**Comment by AeonicAssembler** [comment]
This is working as intended. From the tabletop rules for alternate capstones: "A character can’t select a new capstone if she has previously traded away her class capstone via an archetype."
