### ISSUE TITLE
Bug?: Second Bloodline and Capstone

### ISSUE THREAD

**Issue by TMPhoenix** [Vek17/TabletopTweaks-Base#498]
The Second Bloodline feat gives a character, according to the description, "all the benefits", however, with the capstone selection, it seems the character only gets to pick a single capstone, thus they do not get the second capstone. 

Is this intended behavior?

**Comment by Vek17** [comment]
This is intended because multiple bloodlines are a mess in terms of of support, and there isn't a sane way to really do it otherwise. If you want multiple bloodline capstones disable the setting, and level up to 20 on the bloodline character. After the level up it is safe to re enable and you will keep the capstones if you want those alternate capstones for other characters.

**Comment by TMPhoenix** [comment]
Okay.... Pity, but understandable. I'll close the ticket then.
